# Project: LaberintoPoo
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o Matriz.o Laberinto.o LaberintoPrinter.o LaberintoReader.o ../../../GitHub/P3Lab5_JosueEspinal/CasillaBuscaMinas.o
LINKOBJ  = main.o Matriz.o Laberinto.o LaberintoPrinter.o LaberintoReader.o ../../../GitHub/P3Lab5_JosueEspinal/CasillaBuscaMinas.o
LIBS     = -L"D:/random apps/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"D:/random apps/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/random apps/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"D:/random apps/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/random apps/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/random apps/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"D:/random apps/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/random apps/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/random apps/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = LaberintoPOO.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
DEL      = D:\random apps\Embarcadero\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

Matriz.o: Matriz.cpp
	$(CPP) -c Matriz.cpp -o Matriz.o $(CXXFLAGS)

Laberinto.o: Laberinto.cpp
	$(CPP) -c Laberinto.cpp -o Laberinto.o $(CXXFLAGS)

LaberintoPrinter.o: LaberintoPrinter.cpp
	$(CPP) -c LaberintoPrinter.cpp -o LaberintoPrinter.o $(CXXFLAGS)

LaberintoReader.o: LaberintoReader.cpp
	$(CPP) -c LaberintoReader.cpp -o LaberintoReader.o $(CXXFLAGS)

../../../GitHub/P3Lab5_JosueEspinal/CasillaBuscaMinas.o: ../../../GitHub/P3Lab5_JosueEspinal/CasillaBuscaMinas.cpp
	$(CPP) -c ../../../GitHub/P3Lab5_JosueEspinal/CasillaBuscaMinas.cpp -o ../../../GitHub/P3Lab5_JosueEspinal/CasillaBuscaMinas.o $(CXXFLAGS)
